# Generated by Django 5.2.4 on 2026-02-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Habitación por defecto', max_length=100)),
                ('descripcion', models.TextField(default='Sin descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('capacidad', models.IntegerField(default=1)),
            ],
        ),
    ]
