# Generated by Django 5.2.4 on 2026-02-04 14:15

import django.db.models.deletion
import reservas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_huesped', models.CharField(max_length=120, verbose_name='Nombre del huésped')),
                ('documento', models.CharField(blank=True, default='', help_text='Cédula / pasaporte del huésped (si no tiene, se deja vacío).', max_length=20, verbose_name='Documento')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('fecha_entrada', models.DateField(default=reservas.models.fecha_hoy, verbose_name='Fecha de entrada')),
                ('fecha_salida', models.DateField(default=reservas.models.fecha_manana, verbose_name='Fecha de salida')),
                ('adultos', models.PositiveSmallIntegerField(default=1, verbose_name='Adultos')),
                ('ninos', models.PositiveSmallIntegerField(default=0, verbose_name='Niños')),
                ('tipo_habitacion', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite'), ('familiar', 'Familiar')], default='individual', max_length=20, verbose_name='Tipo de habitación')),
                ('habitacion', models.CharField(default='POR_ASIGNAR', help_text='Ej: 101, 305, A12', max_length=10, verbose_name='Habitación')),
                ('tipo_vehiculo', models.CharField(choices=[('ninguno', 'Sin vehículo'), ('carro', 'Carro'), ('moto', 'Moto'), ('camioneta', 'Camioneta')], default='ninguno', max_length=20, verbose_name='Vehículo')),
                ('placa', models.CharField(blank=True, default='', max_length=10, verbose_name='Placa')),
                ('color_vehiculo', models.CharField(blank=True, default='', max_length=30, verbose_name='Color vehículo')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método de pago')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-creado'],
            },
        ),
    ]
