# Generated by Django 5.2.4 on 2026-02-13 12:43

import django.db.models.deletion
import reservas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('entrada', models.DateField(default=reservas.models.fecha_hoy)),
                ('salida', models.DateField(default=reservas.models.fecha_manana)),
                ('tipo_habitacion', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite'), ('familiar', 'Familiar')], default='individual', max_length=20)),
                ('habitacion', models.CharField(max_length=10)),
                ('tipo_vehiculo', models.CharField(choices=[('ninguno', 'Sin vehículo'), ('carro', 'Carro'), ('moto', 'Moto'), ('camioneta', 'Camioneta')], default='ninguno', max_length=20)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
